#!/usr/bin/env python

from systematics_QSO import *
import sys

if len(sys.argv) != 3:
    print('Usage: mkEsample_systematics_QSO hemisphere version')

zmin = .8
zmax = 2.2
sample = 'QSO' #this probably needs to be changed, I named the files like this
NS = sys.argv[1]
version = sys.argv[2]#'v1.6'
print(NS, version)
if NS == 'N':
	sysmin = 22.4
	sysmax = 23.8
if NS == 'S':
	sysmin = 22.2
	sysmax = 23.6
	
ngvsys_ran(sample,NS,version,'IMAGE_DEPTH_EXT',sysmin,sysmax,zmin,zmax,wm='nosys',band=1)
ngvsys_ran(sample,NS,version,'EB_MINUS_V',0.01,.15,zmin,zmax,wm='wgdepthext')
calcweights(sample,NS,version,zmin=.8,zmax=2.2)

#to call from prompt with, e.g. mkEsample_systematics_QSO 'N' 'v1.6'